.TH "charset" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
charset \- 
.PP
Predefined character set encodings.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Predefined character set encodings. 

Predefined character set definitions: 1) Iso-Latin-1 2) UCS2 (little and big endian, not very efficient implementation) 3) UCS4 (little and big endian, not very efficient implementation) 4) UTF-8 (see http://de.wikipedia.org/wiki/UTF-8 for algorithms) 
.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
