.TH "Exceptions" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exceptions \- 
.PP
Exception classes and structures for error handling in the initialization phase.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtextwolf::throws_exception\fP"
.br
.RI "\fIBase class for structures that can throw exceptions for non recoverable errors in the automata definition. \fP"
.ti -1c
.RI "class \fBtextwolf::exception\fP"
.br
.RI "\fItextwolf exception class \fP"
.in -1c
.SH "Detailed Description"
.PP 
Exception classes and structures for error handling in the initialization phase. 
.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
