.TH "textwolf::charset::IsoLatin1" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::charset::IsoLatin1 \- 
.PP
Character set IsoLatin-1.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBHeadSize\fP = 1, \fBSize\fP = 1, \fBMaxChar\fP = 0xFF }"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned int \fBasize\fP ()"
.br
.ti -1c
.RI "static unsigned int \fBsize\fP (const char *)"
.br
.ti -1c
.RI "static char \fBachar\fP (const char *buf)"
.br
.ti -1c
.RI "static \fBUChar\fP \fBvalue\fP (const char *buf)"
.br
.ti -1c
.RI "static unsigned int \fBprint\fP (\fBUChar\fP chr, char *buf, unsigned int bufsize)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Character set IsoLatin-1. 
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIHeadSize \fP\fP
.TP
\fB\fISize \fP\fP
.TP
\fB\fIMaxChar \fP\fP

.SH "Member Function Documentation"
.PP 
.SS "static char textwolf::charset::IsoLatin1::achar (const char * buf)\fC [inline, static]\fP"
.SS "static unsigned int textwolf::charset::IsoLatin1::asize ()\fC [inline, static]\fP"
.SS "static unsigned int textwolf::charset::IsoLatin1::print (\fBUChar\fP chr, char * buf, unsigned int bufsize)\fC [inline, static]\fP"
.SS "static unsigned int textwolf::charset::IsoLatin1::size (const char *)\fC [inline, static]\fP"
.SS "static \fBUChar\fP textwolf::charset::IsoLatin1::value (const char * buf)\fC [inline, static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
