.TH "textwolf::ScannerStatemachine::Element::Action" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::ScannerStatemachine::Element::Action \- 
.PP
Definition of action fired by the state machine.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBop\fP"
.br
.RI "\fIaction operand \fP"
.ti -1c
.RI "int \fBarg\fP"
.br
.RI "\fIaction argument \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition of action fired by the state machine. 
.SH "Member Data Documentation"
.PP 
.SS "int \fBtextwolf::ScannerStatemachine::Element::Action::arg\fP"
.PP
action argument 
.SS "int \fBtextwolf::ScannerStatemachine::Element::Action::op\fP"
.PP
action operand 

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
