.TH "textwolf::charset::UCS2BE" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::charset::UCS2BE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherits \fBUCS2< ByteOrder::BE >\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
