.TH "textwolf::ScannerStatemachine::Element" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::ScannerStatemachine::Element \- 
.PP
One state in the state machine.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAction\fP"
.br
.RI "\fIDefinition of action fired by the state machine. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElement\fP ()"
.br
.RI "\fIConstructor. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfallbackState\fP"
.br
.RI "\fIstate transition if the event does not match (it belongs to the next state = fallbackState) \fP"
.ti -1c
.RI "int \fBmissError\fP"
.br
.RI "\fIerror code in case of an event that does not match and there is no fallback \fP"
.ti -1c
.RI "\fBAction\fP \fBaction\fP"
.br
.RI "\fIaction executed after entering this state \fP"
.ti -1c
.RI "char \fBnext\fP [NofControlCharacter]"
.br
.RI "\fIfollow state fired by an event (control character type parsed) \fP"
.in -1c
.SH "Detailed Description"
.PP 
One state in the state machine. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "textwolf::ScannerStatemachine::Element::Element ()\fC [inline]\fP"
.PP
Constructor. 
.SH "Member Data Documentation"
.PP 
.SS "\fBAction\fP \fBtextwolf::ScannerStatemachine::Element::action\fP"
.PP
action executed after entering this state 
.SS "int \fBtextwolf::ScannerStatemachine::Element::fallbackState\fP"
.PP
state transition if the event does not match (it belongs to the next state = fallbackState) 
.SS "int \fBtextwolf::ScannerStatemachine::Element::missError\fP"
.PP
error code in case of an event that does not match and there is no fallback 
.SS "char \fBtextwolf::ScannerStatemachine::Element::next\fP[NofControlCharacter]"
.PP
follow state fired by an event (control character type parsed) 

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
