.TH "textwolf::charset" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::charset \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIsoLatin1\fP"
.br
.RI "\fICharacter set IsoLatin-1. \fP"
.ti -1c
.RI "class \fBByteOrder\fP"
.br
.RI "\fIOrder of bytes for wide char character sets. \fP"
.ti -1c
.RI "class \fBUCS2\fP"
.br
.RI "\fICharacter set UCS-2 (little/big endian). \fP"
.ti -1c
.RI "class \fBUCS4\fP"
.br
.RI "\fICharacter set UCS-4 (little/big endian). \fP"
.ti -1c
.RI "struct \fBUCS2LE\fP"
.br
.ti -1c
.RI "struct \fBUCS2BE\fP"
.br
.ti -1c
.RI "struct \fBUCS4LE\fP"
.br
.ti -1c
.RI "struct \fBUCS4BE\fP"
.br
.ti -1c
.RI "class \fBUTF8\fP"
.br
.RI "\fIcharacter set encoding UTF-8 \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
