.TH "textwolf::TextScanner::ControlCharMap" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::TextScanner::ControlCharMap \- 
.PP
Map of ASCII characters to control character identifiers used in the XML scanner automaton.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherits \fBCharMap< ControlCharacter, Undef >\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControlCharMap\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Iterator, class CharSet> class textwolf::TextScanner< Iterator, CharSet >::ControlCharMap"
Map of ASCII characters to control character identifiers used in the XML scanner automaton. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Iterator, class CharSet> \fBtextwolf::TextScanner\fP< Iterator, CharSet >::ControlCharMap::ControlCharMap ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
