.TH "Text Scanner" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Text Scanner \- 
.PP
Preliminary scanning of the input providing a unified view on the input character stream.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtextwolf::TextScanner< Iterator, CharSet >\fP"
.br
.RI "\fIReader for scanning the input character by character. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Preliminary scanning of the input providing a unified view on the input character stream. 
.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
