.TH "textwolf::XMLScanner::IsDQStringCharMap" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::XMLScanner::IsDQStringCharMap \- 
.PP
Defines the set characters belonging to a double quoted string.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherits \fBtextwolf::XMLScanner::IsContentCharMap\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsDQStringCharMap\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class InputIterator, class InputCharSet_ = charset::UTF8, class OutputCharSet_ = charset::UTF8, class EntityMap_ = std::map<const char*,UChar>> class textwolf::XMLScanner< InputIterator, InputCharSet_, OutputCharSet_, EntityMap_ >::IsDQStringCharMap"
Defines the set characters belonging to a double quoted string. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class InputIterator, class InputCharSet_ = charset::UTF8, class OutputCharSet_ = charset::UTF8, class EntityMap_ = std::map<const char*,UChar>> \fBtextwolf::XMLScanner\fP< InputIterator, InputCharSet_, OutputCharSet_, EntityMap_ >::IsDQStringCharMap::IsDQStringCharMap ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
