.TH "textwolf::ControlCharacterM" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::ControlCharacterM \- 
.PP
Map of the enumeration of control characters to their names for debug messages.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const char * \fBname\fP (\fBControlCharacter\fP c)"
.br
.RI "\fIGet the name of a control character as string. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Map of the enumeration of control characters to their names for debug messages. 
.SH "Member Function Documentation"
.PP 
.SS "static const char* textwolf::ControlCharacterM::name (\fBControlCharacter\fP c)\fC [inline, static]\fP"
.PP
Get the name of a control character as string. \fBParameters:\fP
.RS 4
\fIc\fP the control character to map 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
