.TH "textwolf::charset::ByteOrder" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::charset::ByteOrder \- 
.PP
Order of bytes for wide char character sets.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBLE\fP = 1, \fBBE\fP = 2 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Order of bytes for wide char character sets. 
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fILE \fP\fP
little endian 
.TP
\fB\fIBE \fP\fP
big endian 


.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
