.TH "textwolf::CharMap" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::CharMap \- 
.PP
Character map for fast typing of a character byte.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherited by \fBtextwolf::XMLScanner< InputIterator, InputCharSet_, OutputCharSet_, EntityMap_ >::IsContentCharMap\fP, and \fBtextwolf::XMLScanner< InputIterator, InputCharSet_, OutputCharSet_, EntityMap_ >::IsTagCharMap\fP.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBConstant\fP { \fBnullvalue\fP = nullvalue_ }"
.br
.ti -1c
.RI "typedef RESTYPE \fBvaluetype\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCharMap\fP ()"
.br
.RI "\fIConstructor. \fP"
.ti -1c
.RI "\fBCharMap\fP & \fBoperator()\fP (unsigned char from, unsigned char to, \fBvaluetype\fP value)"
.br
.RI "\fIDefine the values of the elements in the interval [from,to]. \fP"
.ti -1c
.RI "\fBCharMap\fP & \fBoperator()\fP (unsigned char at, \fBvaluetype\fP value)"
.br
.RI "\fIDefine the values of the single element at 'at'. \fP"
.ti -1c
.RI "\fBvaluetype\fP \fBoperator[]\fP (unsigned char ii) const "
.br
.RI "\fIRead the element assigned to 'ii'. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "RESTYPE \fBar\fP [RANGE]"
.br
.RI "\fIthe map elements \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename RESTYPE, RESTYPE nullvalue_, int RANGE = 256> class textwolf::CharMap< RESTYPE, nullvalue_, RANGE >"
Character map for fast typing of a character byte. 

\fBTemplate Parameters:\fP
.RS 4
\fIRESTYPE\fP result type of the map 
.br
\fInullvalue_\fP default intitialization value of the map 
.br
\fIRANGE\fP domain of the input values of the map 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "template<typename RESTYPE, RESTYPE nullvalue_, int RANGE = 256> typedef RESTYPE \fBtextwolf::CharMap\fP< RESTYPE, nullvalue_, RANGE >::\fBvaluetype\fP"
.SH "Member Enumeration Documentation"
.PP 
.SS "template<typename RESTYPE, RESTYPE nullvalue_, int RANGE = 256> enum \fBtextwolf::CharMap::Constant\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fInullvalue \fP\fP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename RESTYPE, RESTYPE nullvalue_, int RANGE = 256> \fBtextwolf::CharMap\fP< RESTYPE, nullvalue_, RANGE >::\fBCharMap\fP ()\fC [inline]\fP"
.PP
Constructor. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename RESTYPE, RESTYPE nullvalue_, int RANGE = 256> \fBCharMap\fP& \fBtextwolf::CharMap\fP< RESTYPE, nullvalue_, RANGE >::operator() (unsigned char at, \fBvaluetype\fP value)\fC [inline]\fP"
.PP
Define the values of the single element at 'at'. \fBParameters:\fP
.RS 4
\fIat\fP the input element 
.br
\fIvalue\fP value assigned to the element 'at' 
.RE
.PP

.SS "template<typename RESTYPE, RESTYPE nullvalue_, int RANGE = 256> \fBCharMap\fP& \fBtextwolf::CharMap\fP< RESTYPE, nullvalue_, RANGE >::operator() (unsigned char from, unsigned char to, \fBvaluetype\fP value)\fC [inline]\fP"
.PP
Define the values of the elements in the interval [from,to]. \fBParameters:\fP
.RS 4
\fIfrom\fP start of the input intervall (belongs also to the input) 
.br
\fIto\fP end of the input intervall (belongs also to the input) 
.br
\fIvalue\fP value assigned to all elements in [from,to] 
.RE
.PP

.SS "template<typename RESTYPE, RESTYPE nullvalue_, int RANGE = 256> \fBvaluetype\fP \fBtextwolf::CharMap\fP< RESTYPE, nullvalue_, RANGE >::operator[] (unsigned char ii) const\fC [inline]\fP"
.PP
Read the element assigned to 'ii'. \fBParameters:\fP
.RS 4
\fIii\fP the input element queried 
.RE
.PP
\fBReturns:\fP
.RS 4
the element at 'ii' 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "template<typename RESTYPE, RESTYPE nullvalue_, int RANGE = 256> RESTYPE \fBtextwolf::CharMap\fP< RESTYPE, nullvalue_, RANGE >::\fBar\fP[RANGE]\fC [private]\fP"
.PP
the map elements 

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
