.TH "textwolf::charset::UCS4LE" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::charset::UCS4LE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherits \fBUCS4< ByteOrder::LE >\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
