.TH "XML Path Select" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XML Path Select \- 
.PP
Structures for iterating on the elements typed by XML path selections.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtextwolf::XMLPathSelectAutomaton< CharSet_ >\fP"
.br
.RI "\fIAutomaton to define XML path expressions and assign types (int values) to them. \fP"
.ti -1c
.RI "class \fBtextwolf::XMLPathSelect< InputIterator, InputCharSet_, OutputCharSet_, EntityMap_ >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structures for iterating on the elements typed by XML path selections. 
.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
