.TH "XML Scanner" 3 "11 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XML Scanner \- 
.PP
Structures for iterating on the XML elements.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtextwolf::ScannerStatemachine\fP"
.br
.RI "\fIClass to build up the XML element scanner state machine in a descriptive way. \fP"
.ti -1c
.RI "class \fBtextwolf::XMLScannerBase\fP"
.br
.RI "\fIXML scanner base class for things common for all XML scanners. \fP"
.ti -1c
.RI "class \fBtextwolf::XMLScanner< InputIterator, InputCharSet_, OutputCharSet_, EntityMap_ >\fP"
.br
.RI "\fIXML scanner template that adds the functionality to the statemachine base definition. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Structures for iterating on the XML elements. 
.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
