.TH "charset" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
charset \- 
.PP
Predefined character set encodings.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Predefined character set encodings. 

Predefined character set encoding definitions: 1) Iso-Latin-1 2) UCS2 (little or big endian) 3) UCS4 (little or big endian) 4) UTF-8 (see http://de.wikipedia.org/wiki/UTF-8 for algorithms) 5) UTF-16 (little or big endian, no implicit BOM swapping) see http://en.wikipedia.org/wiki/UTF-16/UCS-2 for algorithms) 
.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
