.TH "State" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
State \- 
.PP
state of the iterator  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SH "Detailed Description"
.PP 
state of the iterator 

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
