.TH "textwolf::ControlCharacterM" 3 "10 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::ControlCharacterM \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const char * \fBname\fP (\fBControlCharacter\fP c)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static const char* textwolf::ControlCharacterM::name (\fBControlCharacter\fP c)\fC [inline, static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
