.TH "textwolf::charset::ByteOrder" 3 "10 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::charset::ByteOrder \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBLE\fP = 1, \fBBE\fP = 2 }"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fILE \fP\fP
.TP
\fB\fIBE \fP\fP



.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
