.TH "textwolf::XMLScannerBase::Statemachine" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::XMLScannerBase::Statemachine \- 
.PP
XML scanner state machine implementation.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherits \fBtextwolf::ScannerStatemachine\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatemachine\fP ()"
.br
.RI "\fIConstructor (defines the state machine completely). \fP"
.in -1c
.SH "Detailed Description"
.PP 
XML scanner state machine implementation. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "textwolf::XMLScannerBase::Statemachine::Statemachine ()\fC [inline]\fP"
.PP
Constructor (defines the state machine completely). 

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
