.TH "textwolf::XMLScannerBase::IsContentCharMap" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::XMLScannerBase::IsContentCharMap \- 
.PP
Defines the set of content token characters.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherits \fBtextwolf::CharMap< bool, false, NofControlCharacter >\fP.
.PP
Inherited by \fBtextwolf::XMLScannerBase::IsDQStringCharMap\fP, and \fBtextwolf::XMLScannerBase::IsSQStringCharMap\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsContentCharMap\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the set of content token characters. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "textwolf::XMLScannerBase::IsContentCharMap::IsContentCharMap ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
