.TH "textwolf::charset::UTF16BE" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::charset::UTF16BE \- 
.PP
UTF-16 big endian character set encoding.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherits \fBUTF16< ByteOrder::BE >\fP.
.SH "Detailed Description"
.PP 
UTF-16 big endian character set encoding. 

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
