.TH "textwolf::XMLPathSelectAutomaton::Token" 3 "10 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::XMLPathSelectAutomaton::Token \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToken\fP ()"
.br
.ti -1c
.RI "\fBToken\fP (const \fBToken\fP &orig)"
.br
.ti -1c
.RI "\fBToken\fP (const \fBState\fP &state, int p_stateidx)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCore\fP \fBcore\fP"
.br
.ti -1c
.RI "int \fBstateidx\fP"
.br
.in -1c

.SS "template<class CharSet_ = charset::UTF8> struct textwolf::XMLPathSelectAutomaton< CharSet_ >::Token"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::Token::Token ()\fC [inline]\fP"
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::Token::Token (const \fBToken\fP & orig)\fC [inline]\fP"
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::Token::Token (const \fBState\fP & state, int p_stateidx)\fC [inline]\fP"
.SH "Member Data Documentation"
.PP 
.SS "template<class CharSet_  = charset::UTF8> \fBCore\fP \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBToken::core\fP"
.SS "template<class CharSet_  = charset::UTF8> int \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBToken::stateidx\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
