.TH "textwolf::XMLScannerBase::Statemachine" 3 "10 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::XMLScannerBase::Statemachine \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherits \fBtextwolf::ScannerStatemachine\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatemachine\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "textwolf::XMLScannerBase::Statemachine::Statemachine ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
