.TH "textwolf::throws_exception" 3 "10 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::throws_exception \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherited by \fBtextwolf::XMLPathSelect< InputIterator, InputCharSet_, OutputCharSet_, EntityMap_ >::Array< int >\fP, \fBtextwolf::XMLPathSelect< InputIterator, InputCharSet_, OutputCharSet_, EntityMap_ >::Array< Scope >\fP, \fBtextwolf::XMLPathSelect< InputIterator, InputCharSet_, OutputCharSet_, EntityMap_ >::Array< Token >\fP, \fBtextwolf::XMLPathSelect< InputIterator, InputCharSet_, OutputCharSet_, EntityMap_ >::Array< unsigned int >\fP, \fBtextwolf::ScannerStatemachine\fP, \fBtextwolf::XMLPathSelect< InputIterator, InputCharSet_, OutputCharSet_, EntityMap_ >\fP, \fBtextwolf::XMLPathSelect< InputIterator, InputCharSet_, OutputCharSet_, EntityMap_ >::Array< Element >\fP, \fBtextwolf::XMLPathSelectAutomaton< CharSet_ >\fP, and \fBtextwolf::XMLPathSelectAutomaton< CharSet_ >::PathElement\fP.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCause\fP { \fBUnknown\fP, \fBDimOutOfRange\fP, \fBStateNumbersNotAscending\fP, \fBInvalidParam\fP, \fBInvalidState\fP, \fBIllegalParam\fP, \fBIllegalAttributeName\fP, \fBOutOfMem\fP, \fBArrayBoundsReadWrite\fP, \fBNotAllowedOperation\fP }"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBtextwolf::throws_exception::Cause\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIUnknown \fP\fP
.TP
\fB\fIDimOutOfRange \fP\fP
.TP
\fB\fIStateNumbersNotAscending \fP\fP
.TP
\fB\fIInvalidParam \fP\fP
.TP
\fB\fIInvalidState \fP\fP
.TP
\fB\fIIllegalParam \fP\fP
.TP
\fB\fIIllegalAttributeName \fP\fP
.TP
\fB\fIOutOfMem \fP\fP
.TP
\fB\fIArrayBoundsReadWrite \fP\fP
.TP
\fB\fINotAllowedOperation \fP\fP



.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
