.TH "textwolf::XMLPathSelect::iterator::Element" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::XMLPathSelect::iterator::Element \- 
.PP
visited current element data of the iterator  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBState\fP { \fBOk\fP, \fBEndOfOutput\fP, \fBEndOfInput\fP, \fBErrorState\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElement\fP ()"
.br
.RI "\fIConstructor. \fP"
.ti -1c
.RI "\fBElement\fP (const \fBEnd\fP &)"
.br
.RI "\fIConstructor for content end iterator. \fP"
.ti -1c
.RI "\fBElement\fP (const \fBElement\fP &orig)"
.br
.RI "\fICopy constructor. \fP"
.ti -1c
.RI "\fBState\fP \fBstate\fP () const "
.br
.RI "\fIGet the iterator state. \fP"
.ti -1c
.RI "int \fBtype\fP () const "
.br
.RI "\fIGet the currently visited element type. \fP"
.ti -1c
.RI "const char * \fBcontent\fP () const "
.br
.RI "\fIGet the currently visited element content. \fP"
.ti -1c
.RI "unsigned int \fBsize\fP () const "
.br
.RI "\fIGet the size of the content of the currently visited element in bytes. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBState\fP \fBm_state\fP"
.br
.RI "\fIcurrent state \fP"
.ti -1c
.RI "int \fBm_type\fP"
.br
.RI "\fIcurrently visited element type \fP"
.ti -1c
.RI "const char * \fBm_content\fP"
.br
.RI "\fIcurrently visited element content \fP"
.ti -1c
.RI "unsigned int \fBm_size\fP"
.br
.RI "\fIsize of the content of the currently visited element in bytes \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBiterator\fP"
.br
.RI "\fIfriend to intialize the elements \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class InputIterator, class InputCharSet_, class OutputCharSet_, class OutputBuffer_, class EntityMap_ = std::map<const char*,UChar>> class textwolf::XMLPathSelect< InputIterator, InputCharSet_, OutputCharSet_, OutputBuffer_, EntityMap_ >::iterator::Element"
visited current element data of the iterator 
.SH "Member Enumeration Documentation"
.PP 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> enum \fBtextwolf::XMLPathSelect::iterator::Element::State\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIOk \fP\fP
normal 
.TP
\fB\fIEndOfOutput \fP\fP
end of output triggered 
.TP
\fB\fIEndOfInput \fP\fP
end of input triggered 
.TP
\fB\fIErrorState \fP\fP
error occurred (identifier as string is in the output token buffer) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> \fBtextwolf::XMLPathSelect\fP< InputIterator, InputCharSet_, OutputCharSet_, OutputBuffer_, EntityMap_ >::iterator::Element::Element ()\fC [inline]\fP"
.PP
Constructor. 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> \fBtextwolf::XMLPathSelect\fP< InputIterator, InputCharSet_, OutputCharSet_, OutputBuffer_, EntityMap_ >::iterator::Element::Element (const \fBEnd\fP &)\fC [inline]\fP"
.PP
Constructor for content end iterator. 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> \fBtextwolf::XMLPathSelect\fP< InputIterator, InputCharSet_, OutputCharSet_, OutputBuffer_, EntityMap_ >::iterator::Element::Element (const \fBElement\fP & orig)\fC [inline]\fP"
.PP
Copy constructor. \fBParameters:\fP
.RS 4
\fIorig\fP element to copy 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> const char* \fBtextwolf::XMLPathSelect\fP< InputIterator, InputCharSet_, OutputCharSet_, OutputBuffer_, EntityMap_ >::iterator::Element::content () const\fC [inline]\fP"
.PP
Get the currently visited element content. 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> unsigned int \fBtextwolf::XMLPathSelect\fP< InputIterator, InputCharSet_, OutputCharSet_, OutputBuffer_, EntityMap_ >::iterator::Element::size () const\fC [inline]\fP"
.PP
Get the size of the content of the currently visited element in bytes. 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> \fBState\fP \fBtextwolf::XMLPathSelect\fP< InputIterator, InputCharSet_, OutputCharSet_, OutputBuffer_, EntityMap_ >::iterator::Element::state () const\fC [inline]\fP"
.PP
Get the iterator state. 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> int \fBtextwolf::XMLPathSelect\fP< InputIterator, InputCharSet_, OutputCharSet_, OutputBuffer_, EntityMap_ >::iterator::Element::type () const\fC [inline]\fP"
.PP
Get the currently visited element type. 
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> friend class \fBiterator\fP\fC [friend]\fP"
.PP
friend to intialize the elements 
.SH "Member Data Documentation"
.PP 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> const char* \fBtextwolf::XMLPathSelect\fP< InputIterator, InputCharSet_, OutputCharSet_, OutputBuffer_, EntityMap_ >::\fBiterator::Element::m_content\fP\fC [private]\fP"
.PP
currently visited element content 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> unsigned int \fBtextwolf::XMLPathSelect\fP< InputIterator, InputCharSet_, OutputCharSet_, OutputBuffer_, EntityMap_ >::\fBiterator::Element::m_size\fP\fC [private]\fP"
.PP
size of the content of the currently visited element in bytes 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> \fBState\fP \fBtextwolf::XMLPathSelect\fP< InputIterator, InputCharSet_, OutputCharSet_, OutputBuffer_, EntityMap_ >::\fBiterator::Element::m_state\fP\fC [private]\fP"
.PP
current state 
.SS "template<class InputIterator , class InputCharSet_ , class OutputCharSet_ , class OutputBuffer_ , class EntityMap_  = std::map<const char*,UChar>> int \fBtextwolf::XMLPathSelect\fP< InputIterator, InputCharSet_, OutputCharSet_, OutputBuffer_, EntityMap_ >::\fBiterator::Element::m_type\fP\fC [private]\fP"
.PP
currently visited element type 

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
