.TH "textwolf::XMLScannerBase::IsSQStringCharMap" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::XMLScannerBase::IsSQStringCharMap \- 
.PP
Defines the set characters belonging to a single quoted string.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherits \fBtextwolf::XMLScannerBase::IsContentCharMap\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsSQStringCharMap\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the set characters belonging to a single quoted string. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "textwolf::XMLScannerBase::IsSQStringCharMap::IsSQStringCharMap ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
