.TH "textwolf::charset::IsoLatin1" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::charset::IsoLatin1 \- 
.PP
Character set IsoLatin-1.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBHeadSize\fP = 1, \fBSize\fP = 1, \fBMaxChar\fP = 0xFF }"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned int \fBasize\fP ()"
.br
.ti -1c
.RI "static unsigned int \fBsize\fP (const char *)"
.br
.ti -1c
.RI "static char \fBachar\fP (const char *buf)"
.br
.ti -1c
.RI "static \fBUChar\fP \fBvalue\fP (const char *buf)"
.br
.RI "\fIparses a unicode character from its serialization in a buffer \fP"
.ti -1c
.RI "template<class Buffer_ > static void \fBprint\fP (\fBUChar\fP chr, Buffer_ &buf)"
.br
.RI "\fIprints a unicode character to a buffer \fP"
.in -1c
.SH "Detailed Description"
.PP 
Character set IsoLatin-1. 
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIHeadSize \fP\fP
.TP
\fB\fISize \fP\fP
.TP
\fB\fIMaxChar \fP\fP

.SH "Member Function Documentation"
.PP 
.SS "static char textwolf::charset::IsoLatin1::achar (const char * buf)\fC [inline, static]\fP"
.SS "static unsigned int textwolf::charset::IsoLatin1::asize ()\fC [inline, static]\fP"
.SS "template<class Buffer_ > static void textwolf::charset::IsoLatin1::print (\fBUChar\fP chr, Buffer_ & buf)\fC [inline, static]\fP"
.PP
prints a unicode character to a buffer \fBTemplate Parameters:\fP
.RS 4
\fIBuffer_\fP STL back insertion sequence 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIchr\fP character to print 
.br
\fIbuf\fP buffer to print to 
.RE
.PP

.SS "static unsigned int textwolf::charset::IsoLatin1::size (const char *)\fC [inline, static]\fP"
.SS "static \fBUChar\fP textwolf::charset::IsoLatin1::value (const char * buf)\fC [inline, static]\fP"
.PP
parses a unicode character from its serialization in a buffer \fBParameters:\fP
.RS 4
\fIbuf\fP buffer to parse the character from 
.RE
.PP
\fBReturns:\fP
.RS 4
the value of the unicode character 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
