.TH "textwolf::charset::UCS2LE" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::charset::UCS2LE \- 
.PP
UCS-2 little endian character set encoding.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherits \fBUCS2< ByteOrder::LE >\fP.
.SH "Detailed Description"
.PP 
UCS-2 little endian character set encoding. 

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
