.TH "textwolf::XMLPathSelectAutomaton::PathElement::Range" 3 "10 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::XMLPathSelectAutomaton::PathElement::Range \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRange\fP (const \fBRange\fP &o)"
.br
.ti -1c
.RI "\fBRange\fP (int p_start, int p_end)"
.br
.ti -1c
.RI "\fBRange\fP (int count)"
.br
.ti -1c
.RI "\fBRange\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstart\fP"
.br
.ti -1c
.RI "int \fBend\fP"
.br
.in -1c

.SS "template<class CharSet_ = charset::UTF8> struct textwolf::XMLPathSelectAutomaton< CharSet_ >::PathElement::Range"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::PathElement::Range::Range (const \fBRange\fP & o)\fC [inline]\fP"
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::PathElement::Range::Range (int p_start, int p_end)\fC [inline]\fP"
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::PathElement::Range::Range (int count)\fC [inline]\fP"
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::PathElement::Range::Range ()\fC [inline]\fP"
.SH "Member Data Documentation"
.PP 
.SS "template<class CharSet_  = charset::UTF8> int \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBPathElement::Range::end\fP"
.SS "template<class CharSet_  = charset::UTF8> int \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBPathElement::Range::start\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
