.TH "textwolf::XMLPathSelectAutomaton::Scope::Range" 3 "10 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::XMLPathSelectAutomaton::Scope::Range \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRange\fP ()"
.br
.ti -1c
.RI "\fBRange\fP (const \fBScope\fP &orig)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBtokenidx_from\fP"
.br
.ti -1c
.RI "unsigned int \fBtokenidx_to\fP"
.br
.ti -1c
.RI "unsigned int \fBfollowidx\fP"
.br
.in -1c

.SS "template<class CharSet_ = charset::UTF8> struct textwolf::XMLPathSelectAutomaton< CharSet_ >::Scope::Range"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::Scope::Range::Range ()\fC [inline]\fP"
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::Scope::Range::Range (const \fBScope\fP & orig)\fC [inline]\fP"
.SH "Member Data Documentation"
.PP 
.SS "template<class CharSet_  = charset::UTF8> unsigned int \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBScope::Range::followidx\fP"
.SS "template<class CharSet_  = charset::UTF8> unsigned int \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBScope::Range::tokenidx_from\fP"
.SS "template<class CharSet_  = charset::UTF8> unsigned int \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBScope::Range::tokenidx_to\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
