.TH "textwolf::XMLPathSelectAutomaton::Core" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::XMLPathSelectAutomaton::Core \- 
.PP
\fBCore\fP of an automaton state definition that is used during XML processing.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCore\fP ()"
.br
.RI "\fIConstructor. \fP"
.ti -1c
.RI "\fBCore\fP (const \fBCore\fP &o)"
.br
.RI "\fICopy constructor. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMask\fP \fBmask\fP"
.br
.RI "\fImask definiting what tokens are matching this state \fP"
.ti -1c
.RI "bool \fBfollow\fP"
.br
.RI "\fItrue, if the state is seeking tokens in all follow scopes in the XML tree \fP"
.ti -1c
.RI "int \fBtypeidx\fP"
.br
.RI "\fItype of the element emitted by this state on a match \fP"
.ti -1c
.RI "int \fBcnt_start\fP"
.br
.RI "\fIlower bound of the element index matching (for index ranges) \fP"
.ti -1c
.RI "int \fBcnt_end\fP"
.br
.RI "\fIupper bound of the element index matching (for index ranges) \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class CharSet_ = charset::UTF8> class textwolf::XMLPathSelectAutomaton< CharSet_ >::Core"
\fBCore\fP of an automaton state definition that is used during XML processing. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::Core::Core ()\fC [inline]\fP"
.PP
Constructor. 
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::Core::Core (const \fBCore\fP & o)\fC [inline]\fP"
.PP
Copy constructor. \fBParameters:\fP
.RS 4
\fIo\fP element to copy 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "template<class CharSet_  = charset::UTF8> int \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBCore::cnt_end\fP"
.PP
upper bound of the element index matching (for index ranges) 
.SS "template<class CharSet_  = charset::UTF8> int \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBCore::cnt_start\fP"
.PP
lower bound of the element index matching (for index ranges) 
.SS "template<class CharSet_  = charset::UTF8> bool \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBCore::follow\fP"
.PP
true, if the state is seeking tokens in all follow scopes in the XML tree 
.SS "template<class CharSet_  = charset::UTF8> \fBMask\fP \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBCore::mask\fP"
.PP
mask definiting what tokens are matching this state 
.SS "template<class CharSet_  = charset::UTF8> int \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBCore::typeidx\fP"
.PP
type of the element emitted by this state on a match 

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
