.TH "textwolf::XMLPathSelectAutomaton::Scope" 3 "10 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::XMLPathSelectAutomaton::Scope \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRange\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScope\fP (const \fBScope\fP &orig)"
.br
.ti -1c
.RI "\fBScope\fP & \fBoperator=\fP (const \fBScope\fP &orig)"
.br
.ti -1c
.RI "\fBScope\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMask\fP \fBmask\fP"
.br
.ti -1c
.RI "\fBMask\fP \fBfollowMask\fP"
.br
.ti -1c
.RI "\fBRange\fP \fBrange\fP"
.br
.in -1c

.SS "template<class CharSet_ = charset::UTF8> struct textwolf::XMLPathSelectAutomaton< CharSet_ >::Scope"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::Scope::Scope (const \fBScope\fP & orig)\fC [inline]\fP"
.SS "template<class CharSet_  = charset::UTF8> \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::Scope::Scope ()\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "template<class CharSet_  = charset::UTF8> \fBScope\fP& \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::Scope::operator= (const \fBScope\fP & orig)\fC [inline]\fP"
.SH "Member Data Documentation"
.PP 
.SS "template<class CharSet_  = charset::UTF8> \fBMask\fP \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBScope::followMask\fP"
.SS "template<class CharSet_  = charset::UTF8> \fBMask\fP \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBScope::mask\fP"
.SS "template<class CharSet_  = charset::UTF8> \fBRange\fP \fBtextwolf::XMLPathSelectAutomaton\fP< CharSet_ >::\fBScope::range\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
