.TH "textwolf::TextScanner::ControlCharMap" 3 "10 Jun 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::TextScanner::ControlCharMap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherits \fBCharMap< ControlCharacter, Undef >\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControlCharMap\fP ()"
.br
.in -1c

.SS "template<class Iterator, class CharSet> struct textwolf::TextScanner< Iterator, CharSet >::ControlCharMap"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Iterator, class CharSet> \fBtextwolf::TextScanner\fP< Iterator, CharSet >::ControlCharMap::ControlCharMap ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
