.TH "textwolf::XMLScannerBase::IsDQStringCharMap" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::XMLScannerBase::IsDQStringCharMap \- 
.PP
Defines the set characters belonging to a double quoted string.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.PP
Inherits \fBtextwolf::XMLScannerBase::IsContentCharMap\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsDQStringCharMap\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the set characters belonging to a double quoted string. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "textwolf::XMLScannerBase::IsDQStringCharMap::IsDQStringCharMap ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
