.TH "textwolf::charset::Encoder" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textwolf::charset::Encoder \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <textwolf.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBencode\fP (\fBUChar\fP chr, char *bufptr, unsigned int bufsize)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static bool textwolf::charset::Encoder::encode (\fBUChar\fP chr, char * bufptr, unsigned int bufsize)\fC [inline, static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
