.TH "Some Helper Structures and Functions" 3 "14 Aug 2011" "textwolf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Some Helper Structures and Functions \- 
.PP
Implements some helpers.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtextwolf::StaticBuffer\fP"
.br
.RI "\fISimple back insertion sequence for storing the outputs of textwolf in a contant size buffer. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implements some helpers. 
.SH "Author"
.PP 
Generated automatically by Doxygen for textwolf from the source code.
